cat << 'EOF' | grep "Berhasil:" | awk '{print $NF}' | sed 's|^\./|https://dalam.web.id/|' | xargs falkon
Berhasil: ./warta-tekno/auto-upgrade-all-npm-packages.html
✅ Berhasil: ./warta-tekno/kenapa-ada-folder-npm-cache.html
✅ Berhasil: ./warta-tekno/cleanup-dependencies.html
✅ Berhasil: ./warta-tekno/branches-di-github.html
✅ Berhasil: ./warta-tekno/cleanup-comparison.html
✅ Berhasil: ./warta-tekno/cleanup.html
✅ Berhasil: ./warta-tekno/mengenal-jenis-domain-name.html
✅ Berhasil: ./warta-tekno/uji-kecepatan-internet-dari-terminal.html
✅ Berhasil: ./warta-tekno/belajar-perintah-curl.html
✅ Berhasil: ./warta-tekno/shutdown-windows-cepat.html
✅ Berhasil: ./warta-tekno/kesimpulan-ai-umkm.html
✅ Berhasil: ./warta-tekno/cleanup-auto.html
✅ Berhasil: ./warta-tekno/main-branch-protection.html
✅ Berhasil: ./warta-tekno/gitignore-nodejs-standar.html
✅ Berhasil: ./warta-tekno/cleanup-tools.html
✅ Berhasil: ./gaya-hidup/hidup-bahagia.html
✅ Berhasil: ./gaya-hidup/cara-mudah-menyelesaikan-psikotes.html
✅ Berhasil: ./gaya-hidup/sikat-gigi-aduk.html
✅ Berhasil: ./gaya-hidup/gaya-hijab-berkendara-motor.html
✅ Berhasil: ./gaya-hidup/angkringan-jogja.html
✅ Berhasil: ./gaya-hidup/stop-piracy-retro.html
✅ Berhasil: ./jejak-sejarah/sabar-menghadapi-ghibah.html
✅ Berhasil: ./jejak-sejarah/maulid-timeline.html
✅ Berhasil: ./jejak-sejarah/saf-shalat.html
✅ Berhasil: ./jejak-sejarah/keutamaan-salam.html
✅ Berhasil: ./jejak-sejarah/maulid-kajian-lengkap.html
✅ Berhasil: ./jejak-sejarah/haki-dalam-islam.html
✅ Berhasil: ./jejak-sejarah/hukum-perayaan-hari-kelahiran-dalam-islam.html
✅ Berhasil: ./jejak-sejarah/maulid-nabi.html
✅ Berhasil: ./jejak-sejarah/insya-allah-janji.html
✅ Berhasil: ./jejak-sejarah/maulid-outline-slides.html
✅ Berhasil: ./jejak-sejarah/Penaklukan-Persia.html
✅ Berhasil: ./lainnya/wigo-balikpapan.html
✅ Berhasil: ./olah-media/menggabungkan-pdf-pdftk.html
✅ Berhasil: ./olah-media/gabung-pdf.html
✅ Berhasil: ./olah-media/menggabungkan-pdf-dengan-pdftk.html
✅ Berhasil: ./olah-media/konversi-pdf-lokal-poppler.html
✅ Berhasil: ./olah-media/imagemagick-konversi-png-ke-jpg-massal.html
✅ Berhasil: ./olah-media/fedora-multimedia.html
✅ Berhasil: ./olah-media/mengubah-format-gambar.html
✅ Berhasil: ./olah-media/imagemagick-resize-semua-foto-dalam-satu-folder-lalu-menyimpannya-di-folder-tujuan.html
✅ Berhasil: ./olah-media/open-document-converter.html
✅ Berhasil: ./olah-media/libreoffice-alternatif-gratis-microsoft-office.html
✅ Berhasil: ./olah-media/mengambil-gambar-dari-pdf.html
✅ Berhasil: ./olah-media/watermark-imagemagick.html
✅ Berhasil: ./olah-media/tutorial-menyatukan-film.html
✅ Berhasil: ./olah-media/kompres-pdf-ghostscript.html
✅ Berhasil: ./olah-media/fedora-multimedia-codec.html
✅ Berhasil: ./olah-media/mengubah-gambar-ke-pdf-imagemagick.html
✅ Berhasil: ./olah-media/ubah-suara-ubuntu-stereo.html
✅ Berhasil: ./olah-media/konversi-m4a-ke-ogg.html
✅ Berhasil: ./olah-media/mengubah-ukuran-banyak-foto-sekaligus-menggunakan-ImageMagick.html
✅ Berhasil: ./opini-sosial/bekerja-dalam-islam.html
✅ Berhasil: ./opini-sosial/mengelola-lisan.html
✅ Berhasil: ./opini-sosial/menjalankan-rencana.html
✅ Berhasil: ./opini-sosial/kasih-ibu-kediri.html
✅ Berhasil: ./sistem-terbuka/keyring.html
✅ Berhasil: ./sistem-terbuka/ubuntu-di-bontang.html
✅ Berhasil: ./sistem-terbuka/rev-linux.html
✅ Berhasil: ./sistem-terbuka/aur-explained.html
✅ Berhasil: ./sistem-terbuka/sejarah-blankon.html
✅ Berhasil: ./sistem-terbuka/ubuntu-25-10-startup-applications.html
✅ Berhasil: ./sistem-terbuka/cara-memperbaiki-GRUB-bootloader-yang-rusak-pada-Debian-dan-turunannya.html
✅ Berhasil: ./sistem-terbuka/desktop-blankon-compiz.html
✅ Berhasil: ./sistem-terbuka/perbaiki-grub-rescue.html
✅ Berhasil: ./sistem-terbuka/alias-linux.html
✅ Berhasil: ./sistem-terbuka/hst-oss.html
✅ Berhasil: ./sistem-terbuka/tar-di-linux.html
✅ Berhasil: ./sistem-terbuka/open-source-indonesia.html
✅ Berhasil: ./sistem-terbuka/linux-mirrors-all.html
✅ Berhasil: ./sistem-terbuka/berapa-banyak-disk-dan-partisi-ter-mount.html
✅ Berhasil: ./sistem-terbuka/hapus-os-ilegal-aman.html
✅ Berhasil: ./sistem-terbuka/remove-old-kernels.html
✅ Berhasil: ./sistem-terbuka/multi-distro-docs.html
✅ Berhasil: ./sistem-terbuka/slackware-mirror.html
✅ Berhasil: ./sistem-terbuka/nixos-mirror.html
✅ Berhasil: ./sistem-terbuka/du-linux-panduan.html
✅ Berhasil: ./sistem-terbuka/ubuntu-not-responding.html
✅ Berhasil: ./sistem-terbuka/conky-bahasa-indonesia.html
✅ Berhasil: ./sistem-terbuka/linux-repo-guide.html
✅ Berhasil: ./sistem-terbuka/oss-di-sekolah.html
✅ Berhasil: ./sistem-terbuka/panduan-instalasi-arch-linux.html
✅ Berhasil: ./sistem-terbuka/ventoy-install-linux.html
✅ Berhasil: ./sistem-terbuka/slackware-nixos-mirror.html
✅ Berhasil: ./sistem-terbuka/presto-yum.html
✅ Berhasil: ./sistem-terbuka/opensuse-mirror.html
✅ Berhasil: ./sistem-terbuka/kpli-balikpapan.html
✅ Berhasil: ./sistem-terbuka/mengganti-kata-dengan-perl.html
✅ Berhasil: ./sistem-terbuka/linux-mirror-guide-all.html
✅ Berhasil: ./sistem-terbuka/training-baris-perintah-linux.html
✅ Berhasil: ./sistem-terbuka/mount-ntfs-caja.html
✅ Berhasil: ./sistem-terbuka/apt-debian-history.html
✅ Berhasil: ./sistem-terbuka/linux-package-manager-formal.html
✅ Berhasil: ./sistem-terbuka/realtek-rtl8723be.html
✅ Berhasil: ./sistem-terbuka/dd-hdd-copy.html
EOF
