#!/bin/bash
echo '🧹 Memulai pembersihan repository...'
rm "ext/indexhtml.js"
rm "ext/check-links-lokal.js"
rm "ext/disqus.js"
rm "ext/generate_indexnow.js"
rm "ext/terjemah.js"
rm "ext/perbaikimetaartikelhtml.js"
rm "ext/header.css"
rm "ext/indexhtml-render.js"
rm "ext/toc.js"
rm "ext/sitemap-init.js"
rm "ext/github-dark.css"
rm "ext/topic-cluster.js"
rm "ext/github.css"
rm "ext/hapus-LD_JSON-bahaya.py"
rm "ext/generate_redirects.py"
rm "ext/indexhtml-util.js"
rm "ext/pesbuk.js"
rm "ext/related-by-topic.js"
rm "ext/github-dark-dimmed.css"
rm "ext/indexhtml-main.js"
rm "ext/related-articles.css"
rm "ext/marquee.js"
rm "ext/visited.js"
rm "ext/related-articles.js"
rm "ext/darkmode.js"
rm "ext/generate-related.js"
rm "ext/inject-meta.js"
echo '✅ Pembersihan selesai!'
