import json
import os
import re
from datetime import datetime, timedelta

# Konfigurasi
OUTPUT_DIR = "artikelx"
LOG_DIR = "mini"
LOG_FILE = os.path.join(LOG_DIR, "posted-aggregat.txt")
JSON_FILE = "artikel.json"

def clean_meta_text(text):
    if not text: return ""
    return re.sub(r'[^\w\s\-\.\,]', '', text)

def get_posted_urls():
    """Membaca daftar URL yang sudah pernah diposting"""
    if not os.path.exists(LOG_FILE):
        return set()
    with open(LOG_FILE, 'r', encoding='utf-8') as f:
        return set(line.strip() for line in f if line.strip())

def save_posted_urls(urls):
    """Menyimpan URL baru ke daftar posted"""
    if not os.path.exists(LOG_DIR):
        os.makedirs(LOG_DIR)
    with open(LOG_FILE, 'a', encoding='utf-8') as f:
        for url in urls:
            f.write(f"{url}\n")

def build_weekly_aggregation():
    # Pastikan folder output ada
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)

    # 1. Baca data JSON
    with open(JSON_FILE, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # Ambil semua artikel dari semua kategori
    all_articles = []
    for category in data:
        all_articles.extend(data[category])

    # 2. Ambil daftar yang sudah pernah tampil
    posted_urls = get_posted_urls()
    
    # 3. Filter: Belum pernah tampil & urutkan Terlama -> Terbaru
    # Kita tidak lagi pakai filter 7 hari jika tujuannya adalah memproses yang 'belum pernah'
    new_articles = []
    for art in all_articles:
        slug = art[1]
        if slug not in posted_urls:
            date_str = art[3].replace('Z', '+00:00')
            new_articles.append({
                'title': art[0],
                'slug': slug,
                'thumb': art[2],
                'date': datetime.fromisoformat(date_str),
                'date_raw': art[3],
                'content': art[4]
            })

    # Urutkan kronologis
    new_articles.sort(key=lambda x: x['date'])

    if not new_articles:
        print("Siappp, tidak ada konten baru untuk diagregasi hari ini.")
        return

    # 4. Generate Konten HTML
    today_str = datetime.now().strftime('%Y-%m-%d')
    file_name = f"agregat-{today_str}.html"
    
    articles_html = ""
    current_batch_urls = []

    for a in new_articles:
        articles_html += f"""
        <section class="article-block">
            <div class="meta"><i class="fa-solid fa-clock"></i> {a['date_raw']}</div>
            <h2>{a['title']}</h2>
            <img src="{a['thumb']}" alt="{clean_meta_text(a['title'])}" class="main-img" loading="lazy">
            <div class="content">
                {a['content']}
            </div>
            <p><a href="https://dalam.web.id/artikel/{a['slug']}" class="read-more">Baca selengkapnya &rarr;</a></p>
            <hr class="separator">
        </section>
        """
        current_batch_urls.append(a['slug'])

    full_html = f"""<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agregasi Mingguan Layar Kosong - {today_str}</title>
    <meta name="description" content="Kumpulan artikel terbaru yang belum pernah tampil sebelumnya di Layar Kosong. Edisi {today_str}.">
    <link rel="canonical" href="https://dalam.web.id/artikelx/{file_name}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <style>
        :root {{ --bg: #ffffff; --text: #1a1a1a; --accent: #d70a53; }}
        @media (prefers-color-scheme: dark) {{ :root {{ --bg: #0d1117; --text: #c9d1d9; --accent: #58a6ff; }} }}
        body {{ font-family: 'Inter', sans-serif; line-height: 1.8; background: var(--bg); color: var(--text); margin: 0; padding: 20px; display: flex; justify-content: center; }}
        .container {{ width: 100%; max-width: 900px; }}
        header {{ text-align: center; border-bottom: 5px solid var(--accent); padding-bottom: 20px; margin-bottom: 40px; }}
        .article-block {{ margin-bottom: 60px; }}
        h1 {{ font-size: 2.5rem; }}
        h2 {{ font-size: 2rem; color: var(--accent); }}
        .main-img {{ width: 100%; border-radius: 12px; margin: 20px 0; object-fit: cover; }}
        .separator {{ border: 0; border-top: 1px dashed #ccc; margin: 40px 0; }}
        .read-more {{ font-weight: bold; color: var(--accent); text-decoration: none; }}
        footer {{ text-align: center; padding: 40px; font-size: 0.9rem; opacity: 0.7; }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>Agregasi Mingguan 🚀</h1>
            <p>Edisi Baru: {today_str} | Kurasi Konten Terpilih</p>
        </header>
        
        {articles_html}

        <footer>
            <p>Generated by Frijal System | Balikpapan</p>
            <p>&copy; 2026 <a href="https://dalam.web.id" style="color:var(--accent)">Layar Kosong</a></p>
        </footer>
    </div>
</body>
</html>"""

    # 5. Simpan file HTML
    with open(os.path.join(OUTPUT_DIR, file_name), 'w', encoding='utf-8') as f:
        f.write(full_html)
    
    # 6. Catat URL yang baru saja diposting agar tidak duplikasi di run berikutnya
    save_posted_urls(current_batch_urls)
    
    print(f"✅ Agregasi sukses: {file_name}")
    print(f"📝 {len(current_batch_urls)} URL baru telah dicatat di {LOG_FILE}")

if __name__ == "__main__":
    build_weekly_aggregation()
