(()=>{document.addEventListener("DOMContentLoaded",async()=>{let B=document.getElementById("iposbrowser");if(!B)return;let j=navigator.userAgent.toLowerCase(),C=j.includes("android")?"Android":/iphone|ipad|ipod/.test(j)?"iOS":j.includes("windows")?"Windows":j.includes("mac")?"macOS":j.includes("linux")?"Linux":"Unknown",E=j.includes("firefox")||j.includes("fxios")?"Firefox":j.includes("edg")?"Edge":j.includes("chrome")||j.includes("crios")?"Chrome":j.includes("safari")?"Safari":"Unknown",F=(q)=>{return`<img src="/ext/icons/${q==="iOS"||q==="macOS"?"macios":q.toLowerCase()}.svg" alt="${q}" onerror="this.src='/ext/icons/unknown.svg'" style="width:14px;height:14px;vertical-align:middle;margin-right:4px;display:inline-block;">`},Q=fetch(`/hit?url=${encodeURIComponent(window.location.pathname)}`).then((q)=>q.ok?q.json():null).catch(()=>null),R=new Promise((q)=>{let J=0,K=setInterval(async()=>{let L=window.siteDataProvider;if(L){clearInterval(K);try{let A=window.location.pathname.split("/").filter(Boolean).pop()||"index.html",W=A.endsWith(".html")?A:`${A}.html`,M=await L.getData();for(let X in M){let O=M[X].find((Y)=>Y[1]===W);if(O)return q(new Date(O[3]).toLocaleDateString("id-ID",{day:"numeric",month:"long",year:"numeric"}))}}catch{}q(null)}else if(++J>30)clearInterval(K),q(null)},100)}),[z,H]=await Promise.all([Q,R]),T='<svg viewBox="0 0 64 64" fill="none" style="width:1em;height:1em;display:block;overflow:visible;"><circle cx="32" cy="32" fill="currentColor" r="5"/><ellipse cx="32" cy="32" rx="24" ry="9" stroke="currentColor" stroke-width="4"/><ellipse transform="rotate(60 32 32)" cx="32" cy="32" rx="24" ry="9" stroke="currentColor" stroke-width="4"/><ellipse transform="rotate(120 32 32)" cx="32" cy="32" rx="24" ry="9" stroke="currentColor" stroke-width="4"/></svg>',U='<svg viewBox="0 0 64 64" fill="none" style="width:1em;height:1em;display:block;overflow:visible;"><rect fill="currentColor" height="48" rx="10" width="48" x="8" y="8"/><circle cx="22" cy="44" fill="white" r="5"/><path d="M17 30c9.4 0 17 7.6 17 17" stroke="white" stroke-linecap="round" stroke-width="6"/><path d="M17 18c16 0 29 13 29 29" stroke="white" stroke-linecap="round" stroke-width="6"/></svg>';B.innerHTML=`
<div id="pagecounter-wrapper" style="display:flex;align-items:center;justify-content:center;flex-wrap:wrap;gap:12px;margin:10px 0 20px;font-size:0.85em;color:var(--text-muted);line-height:1.5;">
<span style="white-space:nowrap;">${F(E)}${E}</span>
<span style="white-space:nowrap;">${F(C)}${C}</span>
${H?`<span style="white-space:nowrap;">\uD83D\uDDD3️ ${H}</span>`:""}
${z?`<span style="white-space:nowrap;"><strong>∞</strong> ${z.v.toLocaleString("id-ID")} <small>~</small> ${z.t.toLocaleString("id-ID")}</span>`:""}
<span style="display:inline-flex;align-items:center;gap:8px;white-space:nowrap;">
<a aria-label="Atom Feed" rel="noopener noreferrer" title="Atom Feed" href="https://dalam.web.id/atom.xml" target="_blank" style="color:#2563eb;text-decoration:none;display:inline-flex;justify-content:center;align-items:center;">
${T}
</a>
<a aria-label="RSS Feed" rel="noopener noreferrer" title="RSS Feed" href="https://dalam.web.id/rss.xml" target="_blank" style="color:#f97316;text-decoration:none;display:inline-flex;justify-content:center;align-items:center;">
${U}
</a>
</span>
</div>`});})();
