const fs = require('fs');
const path = require('path');

const CATEGORIES = ["Sistem Terbuka", "Olah Media", "Jejak Sejarah", "Gaya Hidup", "Opini Sosial", "Warta Tekno"];
const API_KEYS = process.env.GEMINI_KEYS ? process.env.GEMINI_KEYS.split(',').map(k => k.trim()).filter(k => k !== "") : [];
const JSON_PATH = path.join(process.cwd(), 'artikel.json');
const OUTPUT_PATH = path.join(process.cwd(), 'ext/titleToCategory.js');

// Fungsi untuk mengekstrak data dari file JS lama (Regex magic)
function getExistingData() {
    if (!fs.existsSync(OUTPUT_PATH)) return null;
    try {
        const content = fs.readFileSync(OUTPUT_PATH, 'utf8');
        const jsonMatch = content.match(/const categories = (\[[\s\S]*?\]);/);
        return jsonMatch ? JSON.parse(jsonMatch[1]) : null;
    } catch (e) {
        console.warn("⚠️ Gagal membaca file lama, mulai dari nol.");
        return null;
    }
}

async function askGemini(title, apiKey) {
    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`;
    const prompt = `Klasifikasikan judul artikel ini ke dalam salah satu kategori: ${CATEGORIES.join(", ")}. 
    Jawab HANYA dengan NAMA KATEGORI. Jika tidak yakin, jawab "Lainnya".
    Judul: "${title}"`;

    const response = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ contents: [{ parts: [{ text: prompt }] }] })
    });

    if (!response.ok) throw new Error(`Status ${response.status}`);
    const data = await response.json();
    let result = data.candidates[0].content.parts[0].text.trim().replace(/[*_#]/g, '');
    
    const match = CATEGORIES.find(c => result.toLowerCase().includes(c.toLowerCase()));
    return match || "Lainnya";
}

async function main() {
    if (!fs.existsSync(JSON_PATH)) process.exit(1);

    const rawData = JSON.parse(fs.readFileSync(JSON_PATH, 'utf8'));
    const firstGroupName = Object.keys(rawData)[0];
    const articles = rawData[firstGroupName]; 

    // 1. Baca data lama sebagai memori
    const oldData = getExistingData();
    let processedData = {};
    let seenKeywords = new Set();

    // Inisialisasi kategori
    CATEGORIES.concat(["Lainnya"]).forEach(c => processedData[c] = new Set());

    // 2. Jika ada data lama, masukkan keywords-nya ke "seenKeywords" agar tidak diproses ulang
    if (oldData) {
        console.log("📚 Memuat memori dari file lama...");
        oldData.forEach(cat => {
            cat.keywords.forEach(kw => {
                processedData[cat.name]?.add(kw);
                seenKeywords.add(kw);
            });
        });
    }

    let currentKeyIndex = 0;

    for (let i = 0; i < articles.length; i++) {
        const title = articles[i][0];
        const words = title.toLowerCase().replace(/[^\w\s]/g, '').split(/\s+/).filter(w => w.length > 3);
        
        // 3. Cek apakah judul ini sudah terwakili oleh keyword yang ada?
        const isAlreadyKnown = words.some(w => seenKeywords.has(w));

        if (isAlreadyKnown) {
            console.log(`[${i + 1}/${articles.length}] Skip: "${title.substring(0, 30)}..." (Sudah ada di database)`);
            continue; 
        }

        // 4. Jika benar-benar baru, baru tanya Gemini
        let success = false;
        while (!success && currentKeyIndex < API_KEYS.length) {
            try {
                console.log(`[${i + 1}/${articles.length}] 🤖 Tanya AI: ${title.substring(0, 40)}`);
                const result = await askGemini(title, API_KEYS[currentKeyIndex]);
                
                if (processedData[result]) {
                    words.forEach(w => {
                        if (!seenKeywords.has(w)) {
                            processedData[result].add(w);
                            seenKeywords.add(w);
                        }
                    });
                }
                success = true;
                console.log(`   -> Masuk ke: ${result}`);
            } catch (err) {
                console.warn(`⚠️ Key ${currentKeyIndex} limit, ganti key...`);
                currentKeyIndex++;
                await new Promise(r => setTimeout(r, 1000));
            }
        }
        await new Promise(r => setTimeout(r, 1000)); 
    }

    // 5. Susun hasil akhir
    const finalCategories = Object.keys(processedData)
        .filter(name => processedData[name].size > 0)
        .map(name => ({
            name: name,
            keywords: Array.from(processedData[name]).sort()
        }));

    const finalScript = `// Generated by Gemini AI for Layar Kosong
const categories = ${JSON.stringify(finalCategories, null, 2)};

export function titleToCategory(title) {
  const t = title.toLowerCase();
  const found = categories.find(cat =>
    cat.keywords.some(k => t.includes(k))
  );
  return found ? found.name : "Lainnya";
}`;

    if (!fs.existsSync(path.dirname(OUTPUT_PATH))) fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
    fs.writeFileSync(OUTPUT_PATH, finalScript);
    console.log(`\n✅ BERHASIL! Database diperbarui tanpa duplikasi.`);
}

main().catch(() => process.exit(1));
