(()=>{(()=>{let I=/-(sm|md|rg)\.webp$/i,B="auto-lightbox",m=window.matchMedia("(max-width: 767px)"),u=()=>m.matches,r=[],o=0,l=!0,p=!1,e={},E=(t)=>(t.alt||t.title||t.closest("figure")?.querySelector("figcaption")?.textContent||(t.currentSrc||t.src).split("/").pop()?.split("?")[0].split(".")[0]?.replace(/[-_]/g," "))?.trim()||"View Image",L=(t)=>{let i=t.getAttribute("data-full");if(i)return i;let n=t.getAttribute("srcset");if(n){let s="",f=-1,k=n.split(",").map((d)=>d.trim()).filter(Boolean);for(let d of k){let x=d.split(/\s+/),y=x[0],D=x[1]||"";if(!y)continue;let h=D.match(/(\d+)/),v=h?parseInt(h[1],10):0;if(v>=f)f=v,s=y}if(s)return s}return t.currentSrc||t.src},M=(t)=>{if(t.hasAttribute("srcset"))return!1;let n=(t.currentSrc||t.src||"").split("/").pop()?.split("?")[0]||"";return I.test(n)},b=(t)=>{if(M(t))return!1;return t.naturalWidth>=610},w=()=>{l=!0},T=()=>{if(p)return;p=!0,new MutationObserver(w).observe(document.body,{childList:!0,subtree:!0})},A=()=>Array.from(document.images).filter(b),H=()=>{if(e.box||document.getElementById("auto-lightbox"))return;document.body.insertAdjacentHTML("beforeend",`
    <div id="auto-lightbox" role="dialog" aria-modal="true" aria-hidden="true" style="position:fixed;inset:0;background:rgba(0,0,0,0.95);display:none;align-items:center;justify-content:center;transition:opacity .28s ease;opacity:0;backdrop-filter:blur(8px);z-index:100000;">
    <style>
    #auto-lightbox.open { display:flex !important; opacity:1 !important; }
    .lb-btn { background:rgba(255,255,255,0.04); color:#fff; border:none; width:56px; height:56px; border-radius:50%; cursor:pointer; font-size:22px; pointer-events:auto; transition:transform .2s; }
    .lb-btn:hover { transform:scale(1.06); background:rgba(255,255,255,0.12); }
    @media (max-width:767px) { #${"auto-lightbox"} { display:none !important; } }
    </style>
    <div style="position:relative;display:flex;flex-direction:column;align-items:center;gap:12px;max-width:96vw;max-height:94vh;padding:18px;">
    <button id="lb-cls" aria-label="Close" style="position:absolute;top:12px;right:14px;font-size:30px;color:#fff;background:transparent;border:none;cursor:pointer;padding:6px;">&times;</button>
    <img id="lb-img" style="max-width:100%;max-height:78vh;object-fit:contain;border-radius:6px;box-shadow:0 10px 40px rgba(0,0,0,0.6);cursor:zoom-out;transition:opacity .18s;opacity:0;" src="" alt="">
    <div id="lb-cap" aria-live="polite" style="color:#e6eef8;margin-top:6px;font-size:14px;text-align:center;max-width:86vw;line-height:1.4;opacity:0;transition:opacity .18s;font-weight:300;"></div>
    </div>
    <div style="position:absolute;inset:0;display:flex;align-items:center;justify-content:space-between;pointer-events:none;padding:0 2vw;">
    <button id="lb-prv" class="lb-btn" aria-label="Prev">❮</button>
    <button id="lb-nxt" class="lb-btn" aria-label="Next">❯</button>
    </div>
    </div>
    `),e.box=document.getElementById("auto-lightbox"),e.img=document.getElementById("lb-img"),e.cap=document.getElementById("lb-cap"),e.box.addEventListener("click",(t)=>{let i=t.target;if(i===e.box||i.id==="lb-cls"||i.id==="lb-img")c();else if(i.id==="lb-prv")a(-1);else if(i.id==="lb-nxt")a(1)})},g=()=>{let t=r[o];if(!t||!e.img||!e.cap)return;e.img.style.opacity="0",e.cap.style.opacity="0";let i=L(t);e.img.src=i,e.img.alt=t.alt||"View Image",e.cap.textContent=E(t);let n=t.getAttribute("srcset");n?e.img.setAttribute("srcset",n):e.img.removeAttribute("srcset");let s=t.getAttribute("sizes");s?e.img.setAttribute("sizes",s):e.img.removeAttribute("sizes"),e.img.onload=()=>{e.img.style.opacity="1",e.cap.style.opacity="1"}},a=(t)=>{if(r.length>1)o=(o+t+r.length)%r.length,g()},c=()=>{if(!e.box)return;e.box.classList.remove("open"),e.box.setAttribute("aria-hidden","true"),setTimeout(()=>{if(e.img)e.img.src="",e.img.removeAttribute("srcset"),e.img.removeAttribute("sizes")},280)};document.addEventListener("click",(t)=>{if(u())return;let i=t.target;if(i.tagName!=="IMG")return;let n=i;if(!b(n))return;if(n.closest("a"))t.preventDefault();if(H(),T(),l)r=A(),l=!1;if(o=r.indexOf(n),o===-1)return;e.box.classList.add("open"),e.box.setAttribute("aria-hidden","false"),g()}),document.addEventListener("keydown",(t)=>{if(!e.box?.classList.contains("open")||u())return;if(t.key==="ArrowRight")a(1);if(t.key==="ArrowLeft")a(-1);if(t.key==="Escape")c()}),m.addEventListener("change",(t)=>{if(t.matches)c()})})();})();
