(()=>{(()=>{let J={selectors:"img",minWidth:50,mobileBreakpoint:768,excludeSuffix:"-sm.webp",id:"auto-lightbox",closeOnEsc:!0,showOnClickWithinLink:!0},R=[],Z=0,q=null,H=null,X=null,_=!1,$=()=>window.innerWidth<J.mobileBreakpoint;function A(j){if(j.alt&&j.alt.trim())return j.alt.trim();if(j.title&&j.title.trim())return j.title.trim();let E=j.closest("figure");if(E){let P=E.querySelector("figcaption");if(P)return P.innerText.trim()}let K=((j.currentSrc||j.src||"").split("/").pop()||"").split("?")[0].split(".")[0]||"View Image";try{return decodeURIComponent(K).replace(/[-_]/g," ")}catch{return K.replace(/[-_]/g," ")}}function L(){return Array.from(document.querySelectorAll(J.selectors))}function T(){if(document.getElementById(J.id))return;q=document.createElement("div"),q.id=J.id,q.setAttribute("role","dialog"),q.setAttribute("aria-modal","true"),q.setAttribute("aria-hidden","true"),q.style.zIndex="100000",q.innerHTML=`
    <style>
    #${J.id} { position: fixed; inset: 0; background: rgba(0,0,0,0.95); display: none; align-items: center; justify-content: center; transition: opacity 0.28s ease; opacity: 0; backdrop-filter: blur(8px); }
    #${J.id}.open { display:flex; opacity:1; }
    .lb-inner { position: relative; display:flex; flex-direction:column; align-items:center; gap:12px; max-width: 96vw; max-height: 94vh; padding: 18px; box-sizing: border-box; }
    .lb-img { max-width: 100%; max-height: 78vh; object-fit: contain; border-radius: 6px; box-shadow: 0 10px 40px rgba(0,0,0,0.6); cursor: zoom-out; transition: opacity .18s ease; }
    .lb-caption { color: #e6eef8; margin-top: 6px; font-size: 14px; text-align: center; max-width: 86vw; line-height: 1.4; opacity: .95; font-weight: 300; }
    .lb-close { position: absolute; top: 12px; right: 14px; font-size: 30px; color: #fff; background: transparent; border: none; cursor: pointer; padding: 6px; border-radius: 6px; }
    .lb-nav { position: absolute; inset: 0; display:flex; align-items:center; justify-content:space-between; pointer-events:none; }
    .lb-btn { pointer-events:auto; background: rgba(255,255,255,0.04); color: #fff; border: none; width: 56px; height: 56px; border-radius: 50%; cursor: pointer; font-size: 22px; display:flex; align-items:center; justify-content:center; }
    .lb-btn:hover { transform: scale(1.06); background: rgba(255,255,255,0.12); }
    @media (max-width: ${J.mobileBreakpoint-1}px) { #${J.id} { display: none !important; } }
    </style>
    <div class="lb-inner" role="document">
    <button class="lb-close" aria-label="Close lightbox">&times;</button>
    <img class="lb-img" src="" alt="">
    <div class="lb-caption" aria-live="polite"></div>
    </div>
    <div class="lb-nav" aria-hidden="true">
    <button class="lb-btn lb-prev" aria-label="Previous image">❮</button>
    <button class="lb-btn lb-next" aria-label="Next image">❯</button>
    </div>
    `,document.body.appendChild(q),H=q.querySelector(".lb-img"),X=q.querySelector(".lb-caption");let j=q.querySelector(".lb-close"),E=q.querySelector(".lb-prev"),Q=q.querySelector(".lb-next");if(j)j.addEventListener("click",Y);if(H)H.addEventListener("click",Y);if(E)E.addEventListener("click",(K)=>{K.stopPropagation(),w(-1)});if(Q)Q.addEventListener("click",(K)=>{K.stopPropagation(),w(1)});q.addEventListener("click",(K)=>{if(K.target===q)Y()})}function U(j){let E=j.dataset;if(E&&E.full)return E.full;if(j.currentSrc)return j.currentSrc;return j.src||""}function W(j){if(!H)return;let E=j.getAttribute("srcset"),Q=j.getAttribute("sizes");if(E)if(H.setAttribute("srcset",E),Q)H.setAttribute("sizes",Q);else H.removeAttribute("sizes");else H.removeAttribute("srcset"),H.removeAttribute("sizes")}function V(){let j=R[Z];if(!j||!H||!X||!q)return;H.style.opacity="0",X.style.opacity="0";let E=U(j);H.src=E,H.alt=j.alt||j.title||"View Image",X.innerText=A(j),W(j),H.onload=()=>{H&&(H.style.opacity="1"),X&&(X.style.opacity="1")}}function w(j){if(R.length<=1)return;Z=(Z+j+R.length)%R.length,V()}function S(j){if(!q)T();if(!q)return;Z=j,V(),q.classList.add("open"),q.setAttribute("aria-hidden","false"),_=!0;let E=q.querySelector(".lb-close");if(E)E.focus()}function Y(){if(!q)return;q.classList.remove("open"),q.setAttribute("aria-hidden","true"),_=!1,setTimeout(()=>{if(H)H.src="",H.removeAttribute("srcset"),H.removeAttribute("sizes")},260)}function z(){if($())return;T(),document.addEventListener("click",(j)=>{if($())return;let E=j.target;if(!E||E.tagName!=="IMG")return;let Q=E;R=L().filter((D)=>{let k=(D.currentSrc||D.src||"").toLowerCase().includes(J.excludeSuffix),M=D.naturalWidth||0,y=D.width||0;return!k&&(M>=J.minWidth||y>=J.minWidth)});let K=R.indexOf(Q);if(K===-1)return;if(Q.closest("a")&&J.showOnClickWithinLink)j.preventDefault();S(K)}),document.addEventListener("keydown",(j)=>{if(!_||$())return;if(j.key==="ArrowRight")w(1);else if(j.key==="ArrowLeft")w(-1);else if(j.key==="Escape"&&J.closeOnEsc)Y()}),window.addEventListener("resize",()=>{if(!q)return;if($()&&_)Y()})}if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",z);else z()})();})();
