(()=>{(()=>{let R=/-(sm|md|rg)\.webp$/i,U="auto-lightbox",C=window.matchMedia("(max-width: 767px)"),N=()=>C.matches,K=[],V=0,Z=!0,O=!1,B={},T=(j)=>{return(j.alt||j.title||j.closest("figure")?.querySelector("figcaption")?.textContent||(j.currentSrc||j.src).split("/").pop()?.split("?")[0].split(".")[0]?.replace(/[-_]/g," "))?.trim()||"View Image"},W=(j)=>{let H=j.getAttribute("data-full");if(H)return H;let J=j.getAttribute("srcset");if(J){let Q="",X=-1,E=J.split(",").map((f)=>f.trim()).filter(Boolean);for(let f of E){let _=f.split(/\s+/),q=_[0],k=_[1]||"";if(!q)continue;let G=k.match(/(\d+)/),L=G?parseInt(G[1],10):0;if(L>=X)X=L,Q=q}if(Q)return Q}return j.currentSrc||j.src},z=(j)=>{if(j.hasAttribute("srcset"))return!1;let J=(j.currentSrc||j.src||"").split("/").pop()?.split("?")[0]||"";return R.test(J)},P=(j)=>{if(z(j))return!1;return j.naturalWidth>=610},A=()=>{Z=!0},F=()=>{if(O)return;O=!0,new MutationObserver(A).observe(document.body,{childList:!0,subtree:!0})},w=()=>{return Array.from(document.images).filter(P)},D=()=>{if(B.box||document.getElementById("auto-lightbox"))return;document.body.insertAdjacentHTML("beforeend",`
    <div id="auto-lightbox" role="dialog" aria-modal="true" aria-hidden="true" style="position:fixed;inset:0;background:rgba(0,0,0,0.95);display:none;align-items:center;justify-content:center;transition:opacity .28s ease;opacity:0;backdrop-filter:blur(8px);z-index:100000;">
    <style>
    #auto-lightbox.open { display:flex !important; opacity:1 !important; }
    .lb-btn { background:rgba(255,255,255,0.04); color:#fff; border:none; width:56px; height:56px; border-radius:50%; cursor:pointer; font-size:22px; pointer-events:auto; transition:transform .2s; }
    .lb-btn:hover { transform:scale(1.06); background:rgba(255,255,255,0.12); }
    @media (max-width:767px) { #${"auto-lightbox"} { display:none !important; } }
    </style>
    <div style="position:relative;display:flex;flex-direction:column;align-items:center;gap:12px;max-width:96vw;max-height:94vh;padding:18px;">
    <button id="lb-cls" aria-label="Close" style="position:absolute;top:12px;right:14px;font-size:30px;color:#fff;background:transparent;border:none;cursor:pointer;padding:6px;">&times;</button>
    <img id="lb-img" style="max-width:100%;max-height:78vh;object-fit:contain;border-radius:6px;box-shadow:0 10px 40px rgba(0,0,0,0.6);cursor:zoom-out;transition:opacity .18s;opacity:0;" src="" alt="">
    <div id="lb-cap" aria-live="polite" style="color:#e6eef8;margin-top:6px;font-size:14px;text-align:center;max-width:86vw;line-height:1.4;opacity:0;transition:opacity .18s;font-weight:300;"></div>
    </div>
    <div style="position:absolute;inset:0;display:flex;align-items:center;justify-content:space-between;pointer-events:none;padding:0 2vw;">
    <button id="lb-prv" class="lb-btn" aria-label="Prev">❮</button>
    <button id="lb-nxt" class="lb-btn" aria-label="Next">❯</button>
    </div>
    </div>
    `),B.box=document.getElementById("auto-lightbox"),B.img=document.getElementById("lb-img"),B.cap=document.getElementById("lb-cap"),B.box.addEventListener("click",(j)=>{let H=j.target;if(H===B.box||H.id==="lb-cls"||H.id==="lb-img")$();else if(H.id==="lb-prv")Y(-1);else if(H.id==="lb-nxt")Y(1)})},S=()=>{let j=K[V];if(!j||!B.img||!B.cap)return;B.img.style.opacity="0",B.cap.style.opacity="0";let H=W(j);B.img.src=H,B.img.alt=j.alt||"View Image",B.cap.textContent=T(j);let J=j.getAttribute("srcset");J?B.img.setAttribute("srcset",J):B.img.removeAttribute("srcset");let Q=j.getAttribute("sizes");Q?B.img.setAttribute("sizes",Q):B.img.removeAttribute("sizes"),B.img.onload=()=>{B.img.style.opacity="1",B.cap.style.opacity="1"}},Y=(j)=>{if(K.length>1)V=(V+j+K.length)%K.length,S()},$=()=>{if(!B.box)return;B.box.classList.remove("open"),B.box.setAttribute("aria-hidden","true"),setTimeout(()=>{if(B.img)B.img.src="",B.img.removeAttribute("srcset"),B.img.removeAttribute("sizes")},280)};document.addEventListener("click",(j)=>{if(N())return;let H=j.target;if(H.tagName!=="IMG")return;let J=H;if(!P(J))return;if(J.closest("a"))j.preventDefault();if(D(),F(),Z)K=w(),Z=!1;if(V=K.indexOf(J),V===-1)return;B.box.classList.add("open"),B.box.setAttribute("aria-hidden","false"),S()}),document.addEventListener("keydown",(j)=>{if(!B.box?.classList.contains("open")||N())return;if(j.key==="ArrowRight")Y(1);if(j.key==="ArrowLeft")Y(-1);if(j.key==="Escape")$()}),C.addEventListener("change",(j)=>{if(j.matches)$()})})();})();
