(()=>{(function(){function z(){return window.innerWidth<=768||"ontouchstart"in window||navigator.maxTouchPoints>0}function P(H){return H?H.replace(/\.html$/,""):""}function R(){let O=window.location.pathname.split("/").filter(Boolean).pop();if(!O||O==="artikel")return"";return O.endsWith(".html")?O:`${O}.html`}function _(H,O){for(let[Q,j]of Object.entries(O))if(j.some((J)=>J.id===H))return`/${Q.toLowerCase().replace(/\s+/g,"-")}/${H.replace(".html","")}`;return`/${P(H)}`}function $(H,O){for(let[Q,j]of Object.entries(O)){let L=j;if(L.some((J)=>J.id===H))return{name:Q,slug:Q.toLowerCase().replace(/\s+/g,"-"),list:L}}return null}function G(){let H=document.getElementById("related-marquee-container");if(!H)return;let O=getComputedStyle(document.body).backgroundColor,[Q,j,L]=(O.match(/\d+/g)||["0","0","0"]).map(Number),J=0.299*Q+0.587*j+0.114*L;H.classList.toggle("theme-light",J>128)}function q(){let H=document.getElementById("related-marquee-container");if(!H)return;H.addEventListener("click",(O)=>{let j=O.target.closest("a");if(!j)return;let L=j.dataset.articleId;if(!L)return;let J=JSON.parse(localStorage.getItem("read_marquee_articles")||"[]");if(!J.includes(L))J.push(L),localStorage.setItem("read_marquee_articles",JSON.stringify(J))})}function k(){let H=document.getElementById("progress");if(!H)return;let O=()=>{let{documentElement:Q,body:j}=document,L=Q.scrollTop||j.scrollTop,J=Q.scrollHeight||j.scrollHeight,X=Q.clientHeight,V=J-X;H.style.width=V>0?L/V*100+"%":"0%"};window.addEventListener("scroll",O,{passive:!0}),O()}function w(H,O){let Q=document.getElementById("related-marquee-container");if(!Q)return;let j=$(O,H);if(!j)return;let L=j.list.filter((Y)=>Y.id!==O),J=JSON.parse(localStorage.getItem("read_marquee_articles")||"[]"),X=L.filter((Y)=>!J.includes(Y.id));if(X.length===0){Q.innerHTML='<p class="marquee-message">Semua artikel terkait sudah dibaca. \uD83D\uDE0A</p>';return}X.sort(()=>0.5-Math.random());let V=z(),W=X.map((Y)=>{let B=_(Y.id,H),M=V?Y.title:Y.description||Y.title;return`<a href="${B}" data-article-id="${Y.id}" title="${M}">${Y.title}</a> • `}).join("");Q.innerHTML=`<div class="marquee-content">${W.repeat(10)}</div>`;let Z=Q.querySelector(".marquee-content");if(Z){let Y=Z.offsetWidth,B=V?40:75;Z.style.animationDuration=`${Y/2/B}s`}q()}function A(H){let O=document.querySelector(".search-floating-container"),Q=document.getElementById("floatingSearchInput"),j=O?.querySelector(".clear-button"),L=O?.querySelector(".floating-results-container");if(!O||!Q||!j||!L)return;Q.addEventListener("input",()=>{let J=Q.value.trim().toLowerCase();if(j.style.display=J.length?"block":"none",J.length<3){L.style.display="none";return}let X=[];for(let V in H)for(let W of H[V])if((W.title+" "+(W.description||"")).toLowerCase().includes(J))X.push(W);if(X.length>0)L.innerHTML=X.slice(0,5).map((V)=>`
    <a href="${_(V.id,H)}">
    <strong>${V.title}</strong>
    <small>${V.description?V.description.substring(0,60)+"...":"Lihat artikel"}</small>
    </a>
    `).join(""),L.style.display="block";else L.innerHTML='<div class="no-results">❌ Tekan Tombol Enter untuk Selanjutnya...</div>',L.style.display="block"}),Q.addEventListener("keydown",(J)=>{if(J.key==="Enter")J.preventDefault(),window.location.href=`/search/?q=${encodeURIComponent(Q.value)}`}),j.addEventListener("click",()=>{Q.value="",L.style.display="none",j.style.display="none"})}function S(H,O){let Q=document.getElementById("related-articles-grid");if(!Q)return;let j=$(O,H);if(!j)return;let L=j.list.findIndex((Z)=>Z.id===O);if(L===-1)return;let J=j.list.length,X=(L-1+J)%J,V=(L+1)%J,W=document.getElementById("dynamic-nav-container");if(!W)W=document.createElement("div"),W.id="dynamic-nav-container",W.className="floating-nav",Q.appendChild(W);W.innerHTML=`
  <div class="nav-left"><a href="/${j.slug}" class="category-link visible">${j.name}</a></div>
  <div class="nav-right">
  <a href="/" title="Home" class="btn-emoji">\uD83C\uDFE0</a>
  <a href="/sitemap" title="Daftar Isi" class="btn-emoji">\uD83D\uDCC4</a>
  <a href="/feed" title="RSS Feed" class="btn-emoji">\uD83D\uDCE1</a>
  ${J>1?`
    <a href="${_(j.list[X].id,H)}" title="${j.list[X].title}" class="btn-emoji">⏪</a>
    <a href="${_(j.list[V].id,H)}" title="${j.list[V].title}" class="btn-emoji">⏩</a>
    `:""}
    </div>`}function T(){let H=document.getElementById("internal-nav");if(!H)return;let Q=Array.from(document.querySelectorAll("h2, h3, h4")).filter((j)=>{return(j.textContent||"").trim().length>0&&!j.closest(".floating-nav")&&!H.contains(j)});if(Q.length===0){H.style.display="none";return}H.innerHTML='<ul class="nav-list">'+Q.map((j,L)=>{let J=(j.textContent||"").trim();if(!j.id)j.id=J.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")||`section-${L}`;return`<li class="nav-item nav-${j.tagName.toLowerCase()}"><a href="#${j.id}" class="nav-link">${J}</a></li>`}).join("")+"</ul>",H.addEventListener("click",(j)=>{let L=j.target;if(L.tagName.toLowerCase()==="a"&&L.classList.contains("nav-link")){let J=L.getAttribute("href");if(!J||!J.startsWith("#"))return;let X=J.substring(1),V=document.getElementById(X);if(V){let W=V.closest("details");while(W){if(!W.open)W.open=!0;W=W.parentElement?.closest("details")||null}}}})}function y(H,O){let Q=document.getElementById("related-articles-grid");if(!Q)return;let j=$(O,H);if(!j){Q.style.display="none";return}let L=j.list.filter((J)=>J.id!==O).sort(()=>0.5-Math.random()).slice(0,6);Q.innerHTML=L.map((J)=>{let V=(J.image?J.image.replace(/\.[^/.]+$/,"")+"-sm.webp":null)??"/thumbnail-sm.webp",W=J.image?`this.onerror=function(){this.onerror=function(){this.onerror=null;this.src='/thumbnail.webp'};this.src='/thumbnail-sm.webp'};this.src='${J.image}'`:"this.onerror=null;this.src='/thumbnail.webp'";return`
  <div class="rel-card-mini">
  <a href="${_(J.id,H)}">
  <div class="rel-img-mini">
  <img
  src="${V}"
  alt="${J.title}"
  loading="eager"
  decoding="async"
  fetchpriority="low"
  onerror="${W}">
  </div>
  <div class="rel-info-mini">
  <h4>${J.title}</h4>
  </div>
  </a>
  </div>
  `}).join("")}function E(H,O){function Q(j){let L=$(O,H);if(!L||L.list.length<=1)return;let J=L.list.findIndex((Y)=>Y.id===O);if(J===-1)return;let X=L.list.length,V=j==="next"?(J+1)%X:(J-1+X)%X,W=L.list[V].id,Z=_(W,H);if(Z)window.location.href=Z}document.addEventListener("keydown",(j)=>{let L=document.activeElement;if(L.tagName==="INPUT"||L.tagName==="TEXTAREA"||L.isContentEditable||L.closest("#disqus_thread"))return;if(j.ctrlKey&&j.key==="ArrowRight")j.preventDefault(),Q("next");if(j.ctrlKey&&j.key==="ArrowLeft")j.preventDefault(),Q("prev")})}async function K(){while(!window.siteDataProvider)await new Promise((Q)=>setTimeout(Q,100));let H=await window.siteDataProvider.getFor("marquee-url.ts"),O=R();if(H)T(),k(),w(H,O),A(H),y(H,O),S(H,O),E(H,O),G(),window.matchMedia("(prefers-color-scheme: dark)").addEventListener("change",G)}document.readyState==="loading"?document.addEventListener("DOMContentLoaded",K):K()})();})();
