(function(){function P(){return window.innerWidth<=768||"ontouchstart"in window||navigator.maxTouchPoints>0}function R(j){return j?j.replace(/\.html$/,""):""}function k(){let K=window.location.pathname.split("/").filter(Boolean).pop();if(!K||K==="artikel")return"";return K.endsWith(".html")?K:`${K}.html`}function B(j,K){for(let[E,Q]of Object.entries(K))if(Q.some((J)=>J[1]===j))return`/${E.toLowerCase().replace(/\s+/g,"-")}/${j.replace(".html","")}/`;return`/artikel/${R(j)}`}function O(j,K){for(let[E,Q]of Object.entries(K))if(Q.some((J)=>J[1]===j))return{name:E,slug:E.toLowerCase().replace(/\s+/g,"-"),list:Q};return null}function Z(){let j=document.getElementById("related-marquee-container");if(!j)return;let K=getComputedStyle(document.body).backgroundColor,[E,Q,J]=(K.match(/\d+/g)||["0","0","0"]).map(Number),W=0.299*E+0.587*Q+0.114*J;j.classList.toggle("theme-light",W>128)}function w(){let j=document.getElementById("related-marquee-container");if(!j)return;j.addEventListener("click",(K)=>{let Q=K.target.closest("a");if(!Q)return;let J=Q.dataset.articleId;if(!J)return;let W=JSON.parse(localStorage.getItem("read_marquee_articles")||"[]");if(!W.includes(J))W.push(J),localStorage.setItem("read_marquee_articles",JSON.stringify(W))})}function A(){let j=document.getElementById("progress");if(!j)return;let K=()=>{let{documentElement:E,body:Q}=document,J=E.scrollTop||Q.scrollTop,W=E.scrollHeight||Q.scrollHeight,V=E.clientHeight,X=W-V,_=X>0?J/X*100:0;j.style.width=_+"%"};document.addEventListener("scroll",K,{passive:!0}),K()}function U(j,K){let E=document.getElementById("related-marquee-container");if(!E)return;try{let Q=O(K,j);if(!Q)return;let J=Q.list.filter((Y)=>Y[1]!==K),W=JSON.parse(localStorage.getItem("read_marquee_articles")||"[]"),V=J.filter((Y)=>!W.includes(Y[1]));if(V.length===0){E.innerHTML='<p class="marquee-message">Semua artikel terkait sudah dibaca. \uD83D\uDE0A</p>';return}V.sort(()=>0.5-Math.random());let X=" • ",_=P(),G=V.map(([Y,L,,,S])=>{return`<a href="${B(L,j)}" data-article-id="${L}" title="${_?Y:S||Y}">${Y}</a>${X}`}).join("");E.innerHTML=`<div class="marquee-content">${G.repeat(10)}</div>`;let $=E.querySelector(".marquee-content");if($){let Y=$.offsetWidth,L=_?40:75;$.style.animationDuration=`${Y/2/L}s`}w()}catch(Q){console.error("Marquee Error:",Q)}}function y(j){let K=document.querySelector(".search-floating-container"),E=document.getElementById("floatingSearchInput"),Q=K?.querySelector(".clear-button"),J=K?.querySelector(".floating-results-container");if(!K||!E||!Q||!J)return;let W=()=>{let V=E.value.trim();if(V.length>0)window.location.href=`/search/?q=${encodeURIComponent(V)}`};E.addEventListener("input",()=>{let V=E.value.trim();Q.style.display=V.length?"block":"none";let X=V.toLowerCase();if(X.length<3){J.style.display="none";return}let _=[];for(let G in j)for(let $ of j[G])if(($[0]+" "+($[4]||"")).toLowerCase().includes(X))_.push($);if(_.length>0){let $=_.slice(0,5).map((Y)=>`
        <a href="${B(Y[1],j)}">
        <strong>${Y[0]}</strong>
        <small>${Y[4]?Y[4].substring(0,60)+"...":"Lihat artikel"}</small>
        </a>
        `).join("");J.innerHTML=$,J.style.display="block"}else J.innerHTML='<div class="no-results">❌ Tidak ditemukan</div>',J.style.display="block"}),E.addEventListener("keydown",(V)=>{if(V.key==="Enter")V.preventDefault(),W()}),Q.addEventListener("click",()=>{E.value="",J.style.display="none",Q.style.display="none"}),document.addEventListener("click",(V)=>{if(!K.contains(V.target))J.style.display="none"})}function H(j,K){let E=O(K,j);if(!E)return;let Q=E.list.findIndex((_)=>_[1]===K),J=E.list.length,W=(Q-1+J)%J,V=(Q+1)%J,X=document.getElementById("dynamic-nav-container")||document.createElement("div");if(X.id="dynamic-nav-container",X.className="floating-nav",X.innerHTML=`
    <div class="nav-left">
    <a href="/${E.slug}/" class="category-link visible">${E.name}</a>
    </div>
    <div class="nav-right">
    <a href="/" title="Home" class="btn-emoji">\uD83C\uDFE0</a>
    <a href="/sitemap/" title="Daftar Isi" class="btn-emoji">\uD83D\uDCC4</a>
    <a href="/feed/" title="RSS Feed" class="btn-emoji">\uD83D\uDCE1</a>
    ${J>1?`
      <a href="${B(E.list[W][1],j)}" title="${E.list[W][0]}" class="btn-emoji">⏩</a>
      <a href="${B(E.list[V][1],j)}" title="${E.list[V][0]}" class="btn-emoji">⏪</a>
      `:""}
      </div>`,!X.parentElement)document.body.appendChild(X)}function q(){let j=document.getElementById("internal-nav");if(!j)return;let E=Array.from(document.querySelectorAll("h2, h3, h4")).filter((J)=>J.innerText.trim().length>0&&!J.closest(".floating-nav")&&!j.contains(J)&&!J.closest("#layar-kosong-header"));if(E.length===0){j.style.display="none";return}let Q='<ul class="nav-list">';E.forEach((J,W)=>{if(!J.id)J.id=J.innerText.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")||`section-${W}`;let V=J.tagName.toLowerCase();Q+=`
  <li class="nav-item nav-${V}">
  <a href="#${J.id}" class="nav-link">${J.innerText.trim()}</a>
  </li>`}),j.innerHTML=Q+"</ul>"}function M(j,K){let E=document.getElementById("related-articles-grid");if(!E)return;let Q=O(K,j);if(!Q){E.style.display="none";return}let J=Q.list.filter((W)=>W[1]!==K).sort(()=>0.5-Math.random()).slice(0,6);E.innerHTML=J.map(([W,V,X])=>`
    <div class="rel-card-mini">
    <a href="${B(V,j)}">
    <div class="rel-img-mini"><img src="${X||"/thumbnail.webp"}" alt="${W}" loading="lazy" onerror="this.src='/thumbnail.webp'"></div>
    <div class="rel-info-mini"><h4>${W}</h4></div>
    </a>
    </div>
    `).join("")}async function z(){try{q(),A();let j=null,K=sessionStorage.getItem("artikel_data_cache");if(K)j=JSON.parse(K);else{let E=await fetch("/artikel.json");if(!E.ok)throw Error("Gagal memuat artikel.json");j=await E.json(),sessionStorage.setItem("artikel_data_cache",JSON.stringify(j))}if(j){let E=k();U(j,E),M(j,E),y(j),H(j,E),Z(),window.matchMedia("(prefers-color-scheme: dark)").addEventListener("change",Z)}}catch(j){console.error("Layar Kosong Init Error:",j)}}if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",z);else z()})();
