(function(){function E(){return window.innerWidth<=768||"ontouchstart"in window||navigator.maxTouchPoints>0}function L(j){return j?j.replace(/\.html$/,""):""}function w(){let Q=window.location.pathname.split("/").filter(Boolean).pop();if(!Q||Q==="artikel")return"";return Q.endsWith(".html")?Q:`${Q}.html`}function Z(j,Q){for(let[J,V]of Object.entries(Q))if(V.some((K)=>K[1]===j))return`/${J.toLowerCase().replace(/\s+/g,"-")}/${j.replace(".html","")}/`;return`/artikel/${L(j)}`}function O(j,Q){for(let[J,V]of Object.entries(Q))if(V.some((K)=>K[1]===j))return{name:J,slug:J.toLowerCase().replace(/\s+/g,"-"),list:V};return null}function P(){let j=document.getElementById("related-marquee-container");if(!j)return;let Q=getComputedStyle(document.body).backgroundColor,[J,V,K]=(Q.match(/\d+/g)||["0","0","0"]).map(Number),W=0.299*J+0.587*V+0.114*K;j.classList.toggle("theme-light",W>128)}function R(){let j=document.getElementById("related-marquee-container");if(!j)return;j.addEventListener("click",(Q)=>{let V=Q.target.closest("a");if(!V)return;let K=V.dataset.articleId;if(!K)return;let W=JSON.parse(localStorage.getItem("read_marquee_articles")||"[]");if(!W.includes(K))W.push(K),localStorage.setItem("read_marquee_articles",JSON.stringify(W))})}function S(){let j=document.getElementById("progress");if(!j)return;let Q=()=>{let{documentElement:J,body:V}=document,K=J.scrollTop||V.scrollTop,W=J.scrollHeight||V.scrollHeight,X=J.clientHeight,Y=W-X,$=Y>0?K/Y*100:0;j.style.width=$+"%"};document.addEventListener("scroll",Q,{passive:!0}),Q()}function U(j,Q){let J=document.getElementById("related-marquee-container");if(!J)return;try{let V=O(Q,j);if(!V)return;let K=V.list.filter((_)=>_[1]!==Q),W=JSON.parse(localStorage.getItem("read_marquee_articles")||"[]"),X=K.filter((_)=>!W.includes(_[1]));if(X.length===0){J.innerHTML='<p class="marquee-message">Semua artikel terkait sudah dibaca. \uD83D\uDE0A</p>';return}X.sort(()=>0.5-Math.random());let Y=" • ",$=E(),z=X.map(([_,G,,,M])=>{return`<a href="${Z(G,j)}" data-article-id="${G}" title="${$?_:M||_}">${_}</a>${Y}`}).join("");J.innerHTML=`<div class="marquee-content">${z.repeat(10)}</div>`;let B=J.querySelector(".marquee-content");if(B){let _=B.offsetWidth,G=$?40:75;B.style.animationDuration=`${_/2/G}s`}R()}catch(V){console.error("Marquee Error:",V)}}function y(j){let Q=document.querySelector(".search-floating-container"),J=document.getElementById("floatingSearchInput"),V=Q?.querySelector(".clear-button"),K=Q?.querySelector(".floating-results-container");if(!Q||!J||!V||!K)return;let W=()=>{let X=J.value.trim();if(X.length>0)window.location.href=`/search/?q=${encodeURIComponent(X)}`};J.addEventListener("input",()=>{let X=J.value.trim();V.style.display=X.length?"block":"none";let Y=X.toLowerCase();if(Y.length<3){K.style.display="none";return}let $=[];for(let z in j)for(let B of j[z])if((B[0]+" "+(B[4]||"")).toLowerCase().includes(Y))$.push(B);if($.length>0){let B=$.slice(0,5).map((_)=>`
        <a href="${Z(_[1],j)}">
        <strong>${_[0]}</strong>
        <small>${_[4]?_[4].substring(0,60)+"...":"Lihat artikel"}</small>
        </a>
        `).join("");K.innerHTML=B,K.style.display="block"}else K.innerHTML='<div class="no-results">❌ Tidak ditemukan</div>',K.style.display="block"}),J.addEventListener("keydown",(X)=>{if(X.key==="Enter")X.preventDefault(),W()}),V.addEventListener("click",()=>{J.value="",K.style.display="none",V.style.display="none"}),document.addEventListener("click",(X)=>{if(!Q.contains(X.target))K.style.display="none"})}function H(j,Q){let J=O(Q,j);if(!J)return;let V=J.list.findIndex(($)=>$[1]===Q),K=J.list.length,W=(V-1+K)%K,X=(V+1)%K,Y=document.getElementById("dynamic-nav-container")||document.createElement("div");if(Y.id="dynamic-nav-container",Y.className="floating-nav",Y.innerHTML=`
    <div class="nav-left">
    <a href="/${J.slug}/" class="category-link visible">${J.name}</a>
    </div>
    <div class="nav-right">
    <a href="/" title="Home" class="btn-emoji">\uD83C\uDFE0</a>
    <a href="/sitemap/" title="Daftar Isi" class="btn-emoji">\uD83D\uDCC4</a>
    <a href="/feed/" title="RSS Feed" class="btn-emoji">\uD83D\uDCE1</a>
    ${K>1?`
      <a href="${Z(J.list[X][1],j)}" title="${J.list[X][0]}" class="btn-emoji">⏩</a>
      <a href="${Z(J.list[W][1],j)}" title="${J.list[W][0]}" class="btn-emoji">⏪</a>
      `:""}
      </div>`,!Y.parentElement)document.body.appendChild(Y)}function q(){let j=document.getElementById("internal-nav");if(!j)return;let J=Array.from(document.querySelectorAll("h1, h2, h3, h4")).filter((K)=>K.innerText.trim().length>0&&!K.closest(".floating-nav")&&!j.contains(K)&&!K.closest("#layar-kosong-header"));if(J.length===0){j.style.display="none";return}let V='<ul class="nav-list">';J.forEach((K,W)=>{if(!K.id)K.id=K.innerText.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")||`section-${W}`;V+=`<li class="nav-item nav-${K.tagName.toLowerCase()}"><a href="#${K.id}" class="nav-link">${K.innerText.trim()}</a></li>`}),j.innerHTML=V+"</ul>"}function A(j,Q){let J=document.getElementById("related-articles-grid");if(!J)return;let V=O(Q,j);if(!V){J.style.display="none";return}let K=V.list.filter((W)=>W[1]!==Q).sort(()=>0.5-Math.random()).slice(0,6);J.innerHTML=K.map(([W,X,Y])=>`
    <div class="rel-card-mini">
    <a href="${Z(X,j)}">
    <div class="rel-img-mini"><img src="${Y||"/thumbnail.webp"}" alt="${W}" loading="lazy" onerror="this.src='/thumbnail.webp'"></div>
    <div class="rel-info-mini"><h4>${W}</h4></div>
    </a>
    </div>
    `).join("")}async function k(){try{q(),S();let j=null,Q=sessionStorage.getItem("artikel_data_cache");if(Q)j=JSON.parse(Q);else{let J=await fetch("/artikel.json");if(!J.ok)throw Error("Gagal memuat artikel.json");j=await J.json(),sessionStorage.setItem("artikel_data_cache",JSON.stringify(j))}if(j){let J=w();U(j,J),A(j,J),y(j),H(j,J),P(),window.matchMedia("(prefers-color-scheme: dark)").addEventListener("change",P)}}catch(j){console.error("Layar Kosong Init Error:",j)}}if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",k);else k()})();
