name: Delete All Discussions

on:
  workflow_dispatch:

permissions:
  discussions: write # Hanya butuh ini untuk hapus diskusi

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout minimal
        uses: actions/checkout@v4
        with:
          sparse-checkout: 'dapur/sapu-bersih.ts' # Hanya ambil file script saja!
          fetch-depth: 1

      - name: 🚀 Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Run Delete Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: bun run dapur/sapu-bersih.ts
