name: Pixelfed Auto Poster

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *' # Jalan tiap jam 01:00 UTC (Jam 08:00 WIB/ 09:00 WITA)

jobs:
  post-to-pixelfed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest # Langsung tembak versi terbaru dari Bun

      - name: Run Script
        env:
          PIXELFED_TOKEN: ${{ secrets.PIXELFED_TOKEN }}
        run: bun run dapur/post-to-pixelfed.ts
