name: Generate Srcset Prototype

on:
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:          
          fetch-depth: 1
          persist-credentials: true

      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
        with:
          bun-version: latest

      - name: Install Deps
        run: bun install

      - name: Run Generator
        run: bun run srcset-generator.ts      

      - name: Upload Artifacts
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: srcset-results
          path: |
            output/
            img/**/*-sm.webp
          retention-days: 7
          if-no-files-found: warn # Supaya tidak error jika folder output kosong
