name: Generate Srcset Prototype

on:
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:          
          fetch-depth: 1
          persist-credentials: true

      - name: Setup Bun
        uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # v1
        with:
          bun-version: latest

      - name: Install Deps
        run: bun install

      - name: Run Generator
        run: bun run srcset-generator.ts      

      - name: Upload Artifacts
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: srcset-results
          path: |
            output/
            img/**/*-sm.webp
          retention-days: 7
          if-no-files-found: warn # Supaya tidak error jika folder output kosong
